/**
 * Todo Type Definitions
 * Core todo/task types for the task management system
 */

import { UnifiedVideoReference } from './shared'

export interface Todo {
  id: string
  title: string
  description?: string
  priority: 'low' | 'medium' | 'high' | 'urgent'
  status: 'pending' | 'in_progress' | 'completed' | 'blocked' | 'cancelled'
  estimatedMinutes?: number
  category?: string
  dueDate?: string
  generatedFrom?: string
  tags: string[]
  videoReferences: UnifiedVideoReference[]

  // Metadata
  createdAt: string
  updatedAt: string
  completedAt?: string
  createdBy: string
  assignedTo?: string

  // Optional fields for AI integration
  confidence?: number
  autoGenerated?: boolean
  learningObjectives?: string[]
  prerequisites?: string[]
}

export interface TodoFilter {
  status?: Todo['status'][]
  priority?: Todo['priority'][]
  category?: string[]
  assignedTo?: string[]
  tags?: string[]
  hasVideo?: boolean
  dueBefore?: string
  dueAfter?: string
  search?: string
}

export interface TodoSort {
  field: 'title' | 'priority' | 'status' | 'dueDate' | 'createdAt' | 'estimatedMinutes'
  direction: 'asc' | 'desc'
}

export interface CreateTodoRequest {
  title: string
  description?: string
  priority?: Todo['priority']
  category?: string
  dueDate?: string
  estimatedMinutes?: number
  tags?: string[]
  videoReferences?: UnifiedVideoReference[]
  assignedTo?: string
}

export interface UpdateTodoRequest {
  title?: string
  description?: string
  priority?: Todo['priority']
  status?: Todo['status']
  category?: string
  dueDate?: string
  estimatedMinutes?: number
  tags?: string[]
  videoReferences?: UnifiedVideoReference[]
  assignedTo?: string
}